from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.units import inch
import os
from datetime import datetime


def create_pdf(company, industry, analysis):

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/{company.replace(' ','_')}_Risk_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    title = Paragraph(
        "<b><font size=20>AI Risk Assessment Report</font></b>",
        styles["Title"]
    )

    elements.append(title)
    elements.append(Spacer(1, 0.3 * inch))

    info = [
        ["Company", company],
        ["Industry", industry],
        ["Generated On", datetime.now().strftime("%d-%m-%Y %H:%M")]
    ]

    table = Table(info, colWidths=[2 * inch, 4 * inch])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#003366")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),

        ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")
    ]))

    elements.append(table)
    elements.append(Spacer(1, 0.4 * inch))

    heading = Paragraph(
        "<b><font size=16>AI Analysis</font></b>",
        styles["Heading2"]
    )

    elements.append(heading)

    elements.append(
        Paragraph(
            analysis.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 0.5 * inch))

    footer = Paragraph(
        "<font color='grey'>Generated by AI Risk Manager using Google Gemini AI</font>",
        styles["Italic"]
    )

    elements.append(footer)

    doc.build(elements)

    return filename